### PR TITLE
Add lognormal

### PR DESCRIPTION
**Pull request by mattgwwalker**
Added the log-normal distribution.  Note that to deal with the constructor that takes data to form a distribution, I created a function in Common that finds the log of all the values in an array.

The tests were obtained by running the comparable R functions and copy-and-pasting their results.  All tests are passing.

### CODE REVIEW

**Comment by mattgwwalker** [comment]
Ummmm... I'm not really sure I understand your comment.

As far as I can see from a documentation perspective it's "nan".  See https://developer.apple.com/documentation/swift/floatingpoint/1641652-nan

When I tried your suggested change, Xcode 10.1 complains with the error "Instance member 'NaN' cannot be used on type 'Double'"

Although I didn't write that code, I suspect "nan" is correct.

**Comment by mattgwwalker** [comment]
I brought the changes I made to the Travis configuration file into this branch to see if I could generate the same problem you saw with nan versus NaN.

The Travis testing passes with "nan".

**Comment by r0fls** [comment]
Ah ok cool it was just the old Travis version.

Regarding the iOS target, going forward please start checking out new branches from master instead of creating the branch from this one, there’s no need to conflate unrelated changes.

My only other concern here is the array log function (I think it’s called stride). Where did you come up with that? It seems a strange function to have to me...

**Comment by r0fls** [comment]
Actually the function is called logArray. To me that function seems unnecessary and not likely to be used anywhere else. I can give you a concrete example of doing it without it later.

**Comment by mattgwwalker** [comment]
I thought that function would be useful in the same way the function "log" works on arrays in R.  However, I'm not remotely attached to it, and if it's a cause of concern for you, I'll pull it out next.

**Comment by mattgwwalker** [comment]
The logArray function has been removed.  All tests are passing.

**Comment by mattgwwalker** [comment]
@r0fls Would you prefer I merged these changes myself?  Perhaps you're a little busy?  Or would you prefer that I wait for you to merge them?

**Pull request merged**
